# Generated by Django 3.2.6 on 2021-08-22 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_consumer_users_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_img',
            field=models.ImageField(default='default-img.png', null=True, upload_to=''),
        ),
    ]
