# Generated by Django 3.2.6 on 2021-08-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_users_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_img',
            field=models.ImageField(default='profile-default-img.png', null=True, upload_to=''),
        ),
    ]
