# Generated by Django 2.1.1 on 2021-08-21 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('game', 'Game'), ('food/living', 'Food/Living'), ('fashion accessories', 'Fashion Accessories'), ('crafts', 'Crafts'), ('etc', 'ETC')], max_length=30)),
                ('end_date', models.DateField()),
                ('matched', models.BooleanField(default=False)),
                ('liked', models.IntegerField(default=0)),
                ('price', models.IntegerField()),
                ('target_amount', models.IntegerField(default=0)),
                ('target_count', models.IntegerField(default=0)),
                ('comment', models.CharField(max_length=50)),
                ('intent', models.CharField(max_length=800)),
                ('details', models.CharField(max_length=3000)),
                ('counted_user_num', models.IntegerField(default=0)),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('detail_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
