# Generated by Django 3.2.6 on 2021-08-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail_image',
            field=models.ImageField(default='default-img.png', upload_to=''),
        ),
    ]
