# Generated by Django 3.2.6 on 2021-08-22 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_thumbnail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='detail_image',
            field=models.ImageField(blank=True, null=True, upload_to='projects_images'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail_image',
            field=models.ImageField(default='default-img.png', upload_to='projects_images'),
        ),
    ]
